CREATE TABLE user(
  Id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Username VARCHAR(50) NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Date_Of_Birth DATE NOT NULL,
  UNIQUE (Username)
);
CREATE TABLE user_friends(
  user_username VARCHAR(50) NOT NULL,
  friends_username VARCHAR(50) NOT NULL
);